name: Code Camp Event-Driven Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      
      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest

  create_approval_issue:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: trstringer/manual-approval@v1.9.1
        name: manual-approval
        with:
          secret: ${{ secrets.TOKEN }}
          approvers: abhidwivedi2701
          issue-title: "Merge pull request"
          issue-body: "Please approve or deny running terraform apply"
          exclude-workflow-initiator-as-approver: false
          minimum-approvals: 1
          timeout-minutes: 15
  build_docker:
    runs-on: ubuntu-latest
    needs: create_approval_issue
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          docker build -t codecamp-app .
      
      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag codecamp-app dwiabhis/codecamp:latest
          docker push dwiabhis/codecamp:latest
