name: Code Camp Event-Driven Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]
  workflow_dispatch: # Manual trigger

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      
      - name: Run Linter
        run: |
          source venv/bin/activate
          flake8 .
      
      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest

  build_docker:
    runs-on: ubuntu-latest
    needs: lint_and_test
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          docker build -t codecamp-app .
      
      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag codecamp-app mydockerhub/codecamp-app:latest
          docker push mydockerhub/codecamp-app:latest

  welcome_message:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Add Welcome Comment
        uses: actions/github-script@v7
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Welcome to Code Camp! Thanks for opening an issue. We will review it soon.'
            });
